backend:
  name: git-gateway
  repo: smurfazzz/Stoikas
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "pradzia"
    label: "Pagrindinis puslapis"
    files:
      - label: "Index"
        name: "index"
        file: "content/index.md"
        fields:
          - { label: "Antraštė", name: "hero_title", widget: "string" }
          - { label: "Poantraštė", name: "hero_subtitle", widget: "string" }
