backend:
  name: git-gateway
  repo: smurfazzz/Stoikas
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "pradzia"
    label: "Pagrindinis puslapis"
    files:
      - label: "Pagrindinis puslapis"
        name: "index"
        file: "content/index.md"
        fields:
          - { label: "Antraštė", name: "hero_title", widget: "string" }
          - { label: "Poantraštė", name: "hero_subtitle", widget: "string" }
          - { label: "Hero paveikslėlis", name: "hero_image", widget: "image" }

  - name: "kontaktai"
    label: "Kontaktų puslapis"
    files:
      - label: "Kontaktai"
        name: "kontaktai"
        file: "content/kontaktai.md"
        fields:
          - { label: "Puslapio pavadinimas", name: "puslapio_pavadinimas", widget: "string" }
          - { label: "Informacija Tel.", name: "informacija_tel", widget: "string" }
          - { label: "Klubo vadovas", name: "vadovas", widget: "string" }
          - { label: "Vadovo Tel.", name: "vadovo_tel", widget: "string" }
          - { label: "El. paštas", name: "el_pastas", widget: "string" }
          - { label: "Facebook puslapis", name: "facebook", widget: "string" }
          - { label: "Stoiko grupė", name: "grupe", widget: "string" }

  - name: "adresai"
    label: "Treniruočių adresai"
    files:
      - label: "Adresai"
        name: "treniruociu_adresai"
        file: "content/treniruociu-adresai.md"
        fields:
          - { label: "Puslapio pavadinimas", name: "puslapio_pavadinimas", widget: "string" }
          - { label: "Kauno adresas (žemėlapiui)", name: "kaunas_adresas", widget: "string" }
          - { label: "Kauno aprašymas", name: "kaunas_aprasymas", widget: "string" }
          - { label: "Kėdainių adresas (žemėlapiui)", name: "kedainiai_adresas", widget: "string" }
          - { label: "Kėdainių aprašymas", name: "kedainiai_aprasymas", widget: "string" }

  - name: "grafikai"
    label: "Treniruočių grafikai"
    files:
      - label: "Treniruočių grafikai"
        name: "treniruociu_grafikai"
        file: "content/treniruociu-grafikai.md"
        fields:
          - { label: "Puslapio pavadinimas", name: "puslapio_pavadinimas", widget: "string" }

          - label: "Kaunas: Lentelė"
            name: "kaunas_lentele"
            widget: "list"
            label_singular: "Eilutė"
            fields:
              - label: "Langeliai"
                name: "cells"
                widget: "list"
                field:
                  label: "Langas"
                  name: "cell"
                  widget: "string"

          - label: "Kėdainiai: Lentelė"
            name: "kedainiai_lentele"
            widget: "list"
            label_singular: "Eilutė"
            fields:
              - label: "Langeliai"
                name: "cells"
                widget: "list"
                field:
                  label: "Langas"
                  name: "cell"
                  widget: "string"
