backend:
  name: git-gateway
  repo: smurfazzz/Stoikas
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "puslapiai"
    label: "Puslapiai"
    files:
      - label: "1,2% GPM parama"
        name: "gpm"
        file: "1-2proc-gpm-parama.html"
        fields:
          - { label: "HTML turinys", name: "body", widget: "code", default_language: "html" }

      - label: "Kontaktai"
        name: "kontaktai"
        file: "kontaktai.html"
        fields:
          - { label: "HTML turinys", name: "body", widget: "code", default_language: "html" }

      - label: "Treniruotės grafikai"
        name: "grafikai"
        file: "treniruociu-grafikai.html"
        fields:
          - { label: "HTML turinys", name: "body", widget: "code", default_language: "html" }
