backend:
  name: git-gateway
  repo: smurfazzz/Stoikas
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "puslapiai"
    label: "Puslapiai"
    folder: "content"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Pavadinimas", name: "title", widget: "string" }
      - { label: "Hero Tekstas", name: "hero_text", widget: "string" }
      - { label: "Hero Nuotrauka", name: "hero_image", widget: "image" }
      - { label: "Pagrindinis tekstas", name: "body", widget: "markdown" }
