backend:
  name: git-gateway
  repo: smurfazzz/Stoikas
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "pradzia"
    label: "Pagrindinis puslapis"
    files:
      - label: "Pagrindinis puslapis"
        name: "index"
        file: "content/index.md"
        fields:
          - { label: "Antraštė", name: "hero_title", widget: "string" }
          - { label: "Poantraštė", name: "hero_subtitle", widget: "string" }
          - { label: "Hero paveikslėlis", name: "hero_image", widget: "image" }

  - name: "kontaktai"
    label: "Kontaktų puslapis"
    files:
      - label: "Kontaktai"
        name: "kontaktai"
        file: "content/kontaktai.md"
        fields:
          - { label: "Puslapio pavadinimas", name: "puslapio_pavadinimas", widget: "string" }
          - { label: "Informacija Tel.", name: "informacija_tel", widget: "string" }
          - { label: "Klubo vadovas", name: "vadovas", widget: "string" }
          - { label: "Vadovo Tel.", name: "vadovo_tel", widget: "string" }
          - { label: "El. paštas", name: "el_pastas", widget: "string" }
          - { label: "Facebook puslapis", name: "facebook", widget: "string" }
          - { label: "Stoiko grupė", name: "grupe", widget: "string" }

  - name: "adresai"
    label: "Treniruočių adresai"
    files:
      - label: "Adresai"
        name: "treniruociu_adresai"
        file: "content/treniruociu-adresai.md"
        fields:
          - { label: "Puslapio pavadinimas", name: "puslapio_pavadinimas", widget: "string" }
          - { label: "Kauno adresas (žemėlapiui)", name: "kaunas_adresas", widget: "string" }
          - { label: "Kauno aprašymas", name: "kaunas_aprasymas", widget: "string" }
          - { label: "Kėdainių adresas (žemėlapiui)", name: "kedainiai_adresas", widget: "string" }
          - { label: "Kėdainių aprašymas", name: "kedainiai_aprasymas", widget: "string" }

  - name: "grafikai"
    label: "Treniruočių grafikai"
    files:
      - label: "Treniruočių grafikai"
        name: "treniruociu_grafikai"
        file: "content/treniruociu-grafikai.md"
        fields:
          - { label: "Puslapio pavadinimas", name: "puslapio_pavadinimas", widget: "string" }
          - { label: "Kaunas: Antraštė", name: "kaunas_title", widget: "string" }
          - { label: "Kaunas: Įžanga", name: "kaunas_intro", widget: "string" }
          - { label: "Kaunas: Grafiko paveikslėlis", name: "kaunas_img", widget: "image" }
          - { label: "Kaunas: Pastaba", name: "kaunas_note", widget: "string" }
          - { label: "Kaunas: Pastaba 2", name: "kaunas_note_2", widget: "string" }
          - { label: "Kėdainiai: Antraštė", name: "kedainiai_title", widget: "string" }
          - { label: "Kėdainiai: Įžanga", name: "kedainiai_intro", widget: "string" }
          - { label: "Kėdainiai: Grafiko paveikslėlis", name: "kedainiai_img", widget: "image" }
          - { label: "Kėdainiai: Pastaba", name: "kedainiai_note", widget: "string" }

  - name: "norintiems_pabandyti"
    label: "Norintiems pabandyti"
    files:
      - label: "Norintiems pabandyti"
        name: "norintiems_pabandyti"
        file: "content/norintiems-pabandyti.md"
        fields:
          - { label: "Puslapio pavadinimas", name: "puslapio_pavadinimas", widget: "string" }
          - { label: "Hero įžanga", name: "hero_intro", widget: "string" }
          - { label: "Įžangos tekstas", name: "intro_tekstas", widget: "string" }
          - label: "Klubo privalumai"
            name: "privalumai"
            widget: "list"
            field:
              label: "Punktas"
              name: "punktas"
              widget: "string"
          - { label: "Kvietimas", name: "kvietimas", widget: "text" }
          - { label: "Amžiaus grupė", name: "amziaus_grupe", widget: "string" }
          - { label: "Pabaigos tekstas", name: "pabaigos_tekstas", widget: "string" }
